spring:
  application:
    name: TaskManager
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}/${PROD_DB}
    password: ${PROD_DB_PASS}
    username: ${PROD_DB_USER}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  profiles:
    active:
      - prod




