spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}/${PROD_DB}
    password: ${PROD_DB_PASS}
    username: ${PROD_DB_USER}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  jwt-config:
    jwt_secret: ${PROD_JWT_SECRET}
    jwt_expires:  86400000